#ifndef CONFIG_FEATURE_FLAGS_H
#define CONFIG_FEATURE_FLAGS_H

#ifndef SOPWITH_FEATURE_TERRAIN
#define SOPWITH_FEATURE_TERRAIN 1
#endif

#ifndef SOPWITH_FEATURE_FLIGHT
#define SOPWITH_FEATURE_FLIGHT 1
#endif

#ifndef SOPWITH_FEATURE_COLLISIONS
#define SOPWITH_FEATURE_COLLISIONS 0
#endif

#endif